### ISSUE TITLE
Use of role=menuitem and switching aria-haspopup to <a> rather than <li>?

### ISSUE THREAD

**Issue by NateWr** [proteusthemes/WAI-ARIA-Walker_Nav_Menu#1]
Hi primoz, been playing around with this a bit today. This aria stuff can be a real headache.

I'm looking at [this SO post](http://stackoverflow.com/a/12279190/1723499) which includes a helpful breakdown of each element. I've noticed a few things and I thought I'd bring them up to see what you thought. I assume you've dug pretty far into this stuff.
1. From what I gather, the link of each menu item should have a `role=menuitem`. Does that seem right to you?
2. I'm wondering if the `aria-haspopup` and `aria-expanded` attributes are supposed to be on the `<a>` element, rather than the `<li>` element. I think the current situation is technically ok, but it results in a situation whereby keyboard navigation focuses on both the `<li>` and the `<a>` for each item, so you have to tab twice past each one. My thinking is that it would work like this instead:

```
<ul role="menu">
  <li>
    <a id="menu-item-123" role="menuitem" aria-haspopup="true" aria-owns="sub-menu-123">
      Page Link
    </a>
    <ul id="sub-menu-123" role="menu">
      <li>
        <a role="menuitem" aria-describedby="menu-item-123">
          Subpage Link
        </a>
      </li>
    </ul>
  </li>
</ul>
```
1. If I work on this, are you interested in implementing [keyboard controls](http://www.w3.org/WAI/GL/wiki/Using_ARIA_menus#Success_Criteria_2.1.1_Keyboard)?

**Comment by primozcigler** [comment]
Hi @NateWr 

@Prelc did a great research and I only helped with the implementation back then in PHP. For both 1. and 2. we considered your proposed markup, but I also remember that something felt wrong about it. I am sure @Prelc still has some notes about that and he will be able to give you a better explanation.

For 2. I remember the way it is implemented now it's less error prone and technically more correct as well. First tab will focus the `<li>`, which is also opening the submenu (same as `li:hover` is opening the submenu). The next press of the tab will put the focus in the `<a>` which also makes sense, because it gives the user an option to navigate to that link. Put it like that: first tab enters into the entire menu, the second tab enters the parent (first link) of that menu and the following tabs are walking down the submenu items. It reflects properly the DOM and show/hide changes.

> If I work on this, are you interested in implementing keyboard controls?

Most certainly!

**Comment by NateWr** [comment]
Thanks @primozcigler! I've been doing a lot of research too and it's indeed difficult to pick out what's actually supposed to happen with these things. :)

**Comment by primozcigler** [comment]
Something is obvious. We had the `role="menuitem"` at first, but removed it in v1.1.1. Sadly I cannot remember exactly why I did that. But of course there had to be some reason. Look at this commit: https://github.com/proteusthemes/WAI-ARIA-Walker_Nav_Menu/commit/9baa8a61b6bb25fe3db3730abe4a1e7eec0b2fba

**Comment by NateWr** [comment]
Some of the docs I've read this morning suggest not using `role="menuitem"`, because it prevents screen readers from including them in lists of links on the page. Since a website navigation menu doesn't match 1-to-1 the aria role, I guess it requires some adaptation.

_sigh_ :)

**Comment by Prelc** [comment]
Hi @NateWr 

Just like @primozcigler said, we had that role at first, but i can't remember why exactly we removed it. I will try to get some more help from WP community, so we can find best solution together.

**Comment by Prelc** [comment]
Hi @NateWr and @primozcigler 

I asked about that problem on the WordPress accessibility slack channel and `role="menuitem"` can be used only with roles `role="menu"` and `role="menubar"`. But in the specs for menu (http://www.w3.org/TR/wai-aria/roles#menu) they mention:

> A menu is often a list of common actions or functions that the user can invoke. The menu role is appropriate when a list of menu items is presented in a manner _similar to a menu on a desktop application_.

So in that case we shouldn't use any of those roles. Andrea Fercia also mentioned that he wouldn't do that especially because adding menubar or menu doesn't do any "magic" for screen readers and the number of list items is automatically announced by screen readers if you use a list and don't remove its native semantics.

Conclusion: We should and we will also delete `role="menu"` and `role="menubar"`, and not just `role="menuitem",`from walker.

**Comment by NateWr** [comment]
Hi @Prelc,

Nice work following up on that. I had also read similar about the `menu` and `menubar` role but wasn't entirely sure what the best route was. Nice that you got some feedback from someone in the accessibility channel.

**Comment by primozcigler** [comment]
Thank you both for participating, closing this with regards to #2.
